version: '3'
services:

    workspace:
        build:
            context: ./docker/workspace
        links:
            - mongo
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - workspace_pipcache:/root/.cache
            - workspace_pipenv:/root/.local/share/virtualenvs
            - .docker.env:/app/.env
        env_file:
            - .docker.env

    crossbar:
        build:
            context: ./docker/crossbar
        links:
            - mongo
            - redis
        ports:
            - 8080:8080
        volumes:
            - .:/app
            - crossbar_pipcache:/root/.cache
            - crossbar_pipenv:/root/.local/share/virtualenvs
            - .docker.env:/app/.env
        env_file:
            - .docker.env

    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db
        command: mongod  --noauth --bind_ip_all


    redis:
        build:
            context: docker/redis-cluster
            args:
                redis_version: 3.0.7
        ports:
            - "7000:7000"
            - "7001:7001"
        volumes:
            - redis:/data/db
        healthcheck:
          test: ["CMD", "nc", "-zv", "localhost", "7000-7001"]
          timeout: 10s

volumes:
    mongo:
        driver: "local"
    redis:
        driver: "local"
    workspace_pipcache:
        driver: "local"
    workspace_pipenv:
        driver: "local"
    crossbar_pipcache:
        driver: "local"
    crossbar_pipcache:
        driver: "local"
    crossbar_pipenv:
        driver: "local"
    cli_pipcache:
        driver: "local"
    cli_pip:
        driver: "local"
