settings:
  provisioning:
    users:
      - username: mdadmin
        password: this_should_be_replaced_for_production!@#$%^&*()_+1234567890-=
        email: admin@mdstudio.eu
    groups:
      - groupName: mdgroup
        owner: mdadmin
        components:
          - echo
          - lie_amber
          - lie_haddock
          - lie_md
          - lie_plants_dockings
          - lie_propka
          - lie_pylie
          - lie_structures
          
    clients:
      - username: mdadmin
        clientId: Ek@la7\xOhex;5;I$)G'+W<}DL|8h<
        clientSecret: =%FnPYV<U"uh34=[q?TUYZlzIJiLo!
        groups:
          - groupName: mdgroup
            roles:
              owner:
                mdgroup.md.endpoint.testing: ['register']
